# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'IQKeyboardManagerSwift'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GoogleSignIn'
    pod 'SwiftMessages'
end
